- name: Configuration par défaut d'NGINX
  copy:
    src: nginx.conf # pas besoin de préciser de path, il sait qu'il doit chercher dans le dossier files/
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: '0644'
  notify: Restart nginx # Permet d'appeler le handler qui redémarre le service nginx si le fichier "nginx.conf" est modifié