- name: Autoriser le trafic HTTP à travers le firewall
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Ouvrir les ports pour les virtual hosts
  firewalld:
    port: "{{ item.nginx_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ nginx_vhosts }}"
  when: nginx_vhosts is defined
  notify: Restart firewalld # Redémarre le service firewalld si une règle de pare-feu est modifiée