Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "generic/rocky9"
	vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "10.1.1.11"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.gui = true
    end
    vm1.vm.provision "shell", path: "setup.sh"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "generic/rocky9"
	vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "10.1.1.12"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.gui = true
    end
    vm2.vm.provision "shell", path: "setup.sh"
  end

  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  if Vagrant.has_plugin?("vagrant-vbguest")
	config.vbguest.auto_update = false
  end

end