ENV["VAGRANT_EXPERIMENTAL"] = "1"

Vagrant.configure("2") do |config|
  config.vm.box = "rocky9-cloud"
  # On désactive la synchro automatique du dossier courant, pour que ça marche, il faut les Guest Additions
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # Installe Ansible sur la VM cible
  config.vm.provision "shell", inline: <<-SHELL
    useradd ansible
    yum install -y ansible
  SHELL

  # Ajout de la conf cloud-init
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = 'user-data'
  end
end
