Vagrant.configure("2") do |config|
  config.vm.define "webapp1.tp2.cloud" do |webapp1|
    webapp1.vm.box = "generic/rocky9"
    webapp1.vm.hostname = "webapp1.tp2.cloud"
    webapp1.vm.network "private_network", ip: "10.1.1.11"
    webapp1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.gui = true
    end
    webapp1.vm.provision "shell", path: "setup.sh"
  end

  config.vm.define "webapp2.tp2.cloud" do |webapp2|
    webapp2.vm.box = "generic/rocky9"
    webapp2.vm.hostname = "webapp2.tp2.cloud"
    webapp2.vm.network "private_network", ip: "10.1.1.12"
    webapp2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.gui = true
    end
    webapp2.vm.provision "shell", path: "setup.sh"
  end
  
  config.vm.define "rproxy.tp2.cloud" do |rproxy|
    rproxy.vm.box = "generic/rocky9"
    rproxy.vm.hostname = "rproxy.tp2.cloud"
    rproxy.vm.network "private_network", ip: "10.1.1.15"
    rproxy.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.gui = true
    end
    rproxy.vm.provision "shell", path: "setup.sh"
  end	

  config.vm.define "debian.tp2.cloud" do |debian|
    debian.vm.box = "generic/debian11"
    debian.vm.hostname = "debian.tp2.cloud"
    debian.vm.network "private_network", ip: "10.1.1.20"
    debian.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.gui = true
    end
    debian.vm.provision "shell", path: "setup_debian.sh"
  end	
	
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  if Vagrant.has_plugin?("vagrant-vbguest")
	config.vbguest.auto_update = false
  end

end